---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: ibm.power_aix
      - name: ibm.power_ibmi
      - name: ansible.posix
      - name: ansible.utils
      - name: community.general
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    xmltodict
additional_build_files:
  - src: ibmi_module_fix
    dest: plugins/modules
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_galaxy:
    - ADD _build/plugins/modules/ibmi_fix_check.py /usr/share/ansible/collections/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_fix_check.py
    - ADD _build/plugins/modules/ibmi_fix_check.py /usr/share/ansible/collections/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_fix_group_check.py
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN mkdir -p /tmp/work
    - RUN git lfs install --system
